import { AppState } from './types';

export const initialAppState: AppState = {
  setupParams: {
    baseCurrency: 'USD',
    sharedCostAllocationPolicy: 'EQUAL_SHARE',
    fxRates: [
      { currency: 'USD', rateToUSD: 1.0 },
      { currency: 'MXN', rateToUSD: 0.058 },
      { currency: 'EUR', rateToUSD: 1.08 },
      { currency: 'THB', rateToUSD: 0.029 },
      { currency: 'CAD', rateToUSD: 0.74 },
      { currency: 'GBP', rateToUSD: 1.27 },
      { currency: 'CNY', rateToUSD: 0.138 },
    ],
    transactionTypeMappings: [
      { transactionType: 'CUSTOMER_INVOICE', financialTreatment: 'Revenue' },
      { transactionType: 'DEMURRAGE_REVENUE', financialTreatment: 'Revenue' },
      { transactionType: 'VENDOR_COST', financialTreatment: 'COGS' },
      { transactionType: 'CARRIER_FREIGHT', financialTreatment: 'COGS' },
      { transactionType: 'TERMINAL_HANDLING', financialTreatment: 'COGS' },
      { transactionType: 'DRAYAGE_FEE', financialTreatment: 'COGS' },
      { transactionType: 'CUSTOMS_DUTY', financialTreatment: 'COGS' },
      { transactionType: 'INSPECTION_COST', financialTreatment: 'COGS' },
      { transactionType: 'BANK_FEE', financialTreatment: 'Bank Fee' },
      { transactionType: 'WIRE_TRANSFER_FEE', financialTreatment: 'Bank Fee' },
      { transactionType: 'RECOVERABLE_DEPOSIT', financialTreatment: 'Deposit' },
      { transactionType: 'CONTAINER_BOND', financialTreatment: 'Deposit' },
    ],
  },
  bookings: [
    {
      bookingId: 'BFLCOMEINSMAC001',
      orderDate: '2026-07-01',
      customerName: 'Apex Logistics Corp',
      bookingStatus: 'Completed',
    },
    {
      bookingId: 'BFLCOMEINSMAC002',
      orderDate: '2026-07-10',
      customerName: 'TransAtlantic Trading Co',
      bookingStatus: 'In Transit',
    },
    {
      bookingId: 'BFLCOMEINSMAC003',
      orderDate: '2026-07-18',
      customerName: 'Pacific Rim Electronics',
      bookingStatus: 'Customs Hold',
    },
    {
      bookingId: 'BFLCOMEINSMAC004',
      orderDate: '2026-08-01',
      customerName: 'Nordic Home Goods',
      bookingStatus: 'In Transit',
    },
    {
      bookingId: 'BFLCOMEINSMAC005',
      orderDate: '2026-08-05',
      customerName: 'Vanguard Retailers',
      bookingStatus: 'Booked',
    },
  ],
  containers: [
    {
      containerId: 'MSCU1234567',
      bookingId: 'BFLCOMEINSMAC001',
      sizeType: '40HQ',
      containerStatus: 'Delivered',
    },
    {
      containerId: 'MSCU7654321',
      bookingId: 'BFLCOMEINSMAC001',
      sizeType: '40HQ',
      containerStatus: 'Delivered',
    },
    {
      containerId: 'CMAU9876543',
      bookingId: 'BFLCOMEINSMAC002',
      sizeType: '20GP',
      containerStatus: 'In Transit',
    },
    {
      containerId: 'EGLU5544332',
      bookingId: 'BFLCOMEINSMAC003',
      sizeType: '40HQ',
      containerStatus: 'Customs Hold',
    },
    {
      containerId: 'EGLU5544333',
      bookingId: 'BFLCOMEINSMAC003',
      sizeType: '40HQ',
      containerStatus: 'Customs Hold',
    },
    {
      containerId: 'EGLU5544334',
      bookingId: 'BFLCOMEINSMAC003',
      sizeType: '40HQ',
      containerStatus: 'Customs Hold',
    },
    {
      containerId: 'OOLU1122334',
      bookingId: 'BFLCOMEINSMAC004',
      sizeType: '20GP',
      containerStatus: 'In Transit',
    },
    {
      containerId: 'COSU9988776',
      bookingId: 'BFLCOMEINSMAC005',
      sizeType: '40GP',
      containerStatus: 'Booked',
    },
  ],
  services: [
    {
      serviceCode: 'OCEAN_FRT',
      serviceName: 'Main Line Ocean Freight',
      category: 'Freight',
    },
    {
      serviceCode: 'ORIGIN_THC',
      serviceName: 'Terminal Handling Charge - Origin',
      category: 'Origin Service',
    },
    {
      serviceCode: 'DEST_THC',
      serviceName: 'Terminal Handling Charge - Destination',
      category: 'Destination Service',
    },
    {
      serviceCode: 'DRAYAGE',
      serviceName: 'Port Drayage & Local Haulage',
      category: 'Destination Service',
    },
    {
      serviceCode: 'CUSTOMS_CLR',
      serviceName: 'Customs Clearance & Import Filing',
      category: 'Customs',
    },
    {
      serviceCode: 'INSPEC_FEE',
      serviceName: 'Physical Cargo Inspection Fee',
      category: 'Customs',
    },
    {
      serviceCode: 'DOC_FEE',
      serviceName: 'Bill of Lading Documentation Fee',
      category: 'Documentation',
    },
    {
      serviceCode: 'BANK_WIRE',
      serviceName: 'International Wire Transfer Fee',
      category: 'Finance',
    },
    {
      serviceCode: 'SECURITY_DEP',
      serviceName: 'Equipment Protection Security Deposit',
      category: 'Finance',
    },
  ],
  transactions: [
    // Booking 001 - Apex Logistics (2 containers: MSCU1234567, MSCU7654321)
    {
      transactionId: 'TXN-10001',
      bookingId: 'BFLCOMEINSMAC001',
      containerId: '',
      transactionDate: '2026-07-02',
      customerVendor: 'Apex Logistics Corp',
      serviceCode: 'OCEAN_FRT',
      description: 'All-inclusive ocean freight billing',
      transactionType: 'CUSTOMER_INVOICE',
      allocationLevel: 'BOOKING',
      originalAmount: 12500,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-10002',
      bookingId: 'BFLCOMEINSMAC001',
      containerId: '',
      transactionDate: '2026-07-03',
      customerVendor: 'MSC Mediterranean Shipping',
      serviceCode: 'OCEAN_FRT',
      description: 'Port-to-port ocean carrier freight cost',
      transactionType: 'CARRIER_FREIGHT',
      allocationLevel: 'BOOKING',
      originalAmount: 8200,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-10003',
      bookingId: 'BFLCOMEINSMAC001',
      containerId: 'MSCU1234567',
      transactionDate: '2026-07-05',
      customerVendor: 'Manzanillo Terminal Operations',
      serviceCode: 'ORIGIN_THC',
      description: 'Container 1 origin terminal handling',
      transactionType: 'TERMINAL_HANDLING',
      allocationLevel: 'CONTAINER',
      originalAmount: 8500,
      currency: 'MXN',
      manualFxRate: 0, // Uses Setup_Params MXN rate 0.058 -> $493.00
    },
    {
      transactionId: 'TXN-10004',
      bookingId: 'BFLCOMEINSMAC001',
      containerId: 'MSCU7654321',
      transactionDate: '2026-07-05',
      customerVendor: 'Manzanillo Terminal Operations',
      serviceCode: 'ORIGIN_THC',
      description: 'Container 2 origin terminal handling',
      transactionType: 'TERMINAL_HANDLING',
      allocationLevel: 'CONTAINER',
      originalAmount: 8500,
      currency: 'MXN',
      manualFxRate: 0, // -> $493.00
    },
    {
      transactionId: 'TXN-10005',
      bookingId: 'BFLCOMEINSMAC001',
      containerId: '',
      transactionDate: '2026-07-12',
      customerVendor: 'City National Bank',
      serviceCode: 'BANK_WIRE',
      description: 'Overseas vendor wire fee',
      transactionType: 'WIRE_TRANSFER_FEE',
      allocationLevel: 'BOOKING',
      originalAmount: 45,
      currency: 'USD',
      manualFxRate: 0,
    },

    // Booking 002 - TransAtlantic Trading (1 container: CMAU9876543)
    {
      transactionId: 'TXN-20001',
      bookingId: 'BFLCOMEINSMAC002',
      containerId: 'CMAU9876543',
      transactionDate: '2026-07-11',
      customerVendor: 'TransAtlantic Trading Co',
      serviceCode: 'OCEAN_FRT',
      description: '20GP Ocean freight invoice',
      transactionType: 'CUSTOMER_INVOICE',
      allocationLevel: 'CONTAINER',
      originalAmount: 6800,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-20002',
      bookingId: 'BFLCOMEINSMAC002',
      containerId: 'CMAU9876543',
      transactionDate: '2026-07-12',
      customerVendor: 'CMA CGM Line',
      serviceCode: 'OCEAN_FRT',
      description: 'Ocean carrier slot cost in EUR',
      transactionType: 'CARRIER_FREIGHT',
      allocationLevel: 'CONTAINER',
      originalAmount: 3800,
      currency: 'EUR',
      manualFxRate: 0, // Uses EUR rate 1.08 -> $4,104.00
    },
    {
      transactionId: 'TXN-20003',
      bookingId: 'BFLCOMEINSMAC002',
      containerId: 'CMAU9876543',
      transactionDate: '2026-07-15',
      customerVendor: 'Rotterdam Port Logistics',
      serviceCode: 'DEST_THC',
      description: 'Destination THC invoice in EUR',
      transactionType: 'TERMINAL_HANDLING',
      allocationLevel: 'CONTAINER',
      originalAmount: 320,
      currency: 'EUR',
      manualFxRate: 0, // -> $345.60
    },
    {
      transactionId: 'TXN-20004',
      bookingId: 'BFLCOMEINSMAC002',
      containerId: '',
      transactionDate: '2026-07-16',
      customerVendor: 'HSBC Bank',
      serviceCode: 'BANK_WIRE',
      description: 'FX Settlement Bank Fee',
      transactionType: 'BANK_FEE',
      allocationLevel: 'BOOKING',
      originalAmount: 35,
      currency: 'USD',
      manualFxRate: 0,
    },

    // Booking 003 - Pacific Rim (3 containers: EGLU5544332, EGLU5544333, EGLU5544334)
    {
      transactionId: 'TXN-30001',
      bookingId: 'BFLCOMEINSMAC003',
      containerId: '',
      transactionDate: '2026-07-19',
      customerVendor: 'Pacific Rim Electronics',
      serviceCode: 'OCEAN_FRT',
      description: '3x40HQ Freight & Customs Service Package',
      transactionType: 'CUSTOMER_INVOICE',
      allocationLevel: 'BOOKING',
      originalAmount: 28500,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-30002',
      bookingId: 'BFLCOMEINSMAC003',
      containerId: '',
      transactionDate: '2026-07-20',
      customerVendor: 'Evergreen Marine',
      serviceCode: 'OCEAN_FRT',
      description: 'Carrier ocean freight cost',
      transactionType: 'CARRIER_FREIGHT',
      allocationLevel: 'BOOKING',
      originalAmount: 17400,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-30003',
      bookingId: 'BFLCOMEINSMAC003',
      containerId: 'EGLU5544332',
      transactionDate: '2026-07-24',
      customerVendor: 'US Customs & Border Protection',
      serviceCode: 'INSPEC_FEE',
      description: 'Intensive physical examination charge',
      transactionType: 'INSPECTION_COST',
      allocationLevel: 'CONTAINER',
      originalAmount: 1250,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-30004',
      bookingId: 'BFLCOMEINSMAC003',
      containerId: '',
      transactionDate: '2026-07-25',
      customerVendor: 'Port Equipment Authority',
      serviceCode: 'SECURITY_DEP',
      description: 'Refundable equipment bond deposit',
      transactionType: 'CONTAINER_BOND',
      allocationLevel: 'BOOKING',
      originalAmount: 3000,
      currency: 'USD',
      manualFxRate: 0, // Deposit treatment
    },

    // Booking 004 - Nordic Home Goods (1 container: OOLU1122334)
    {
      transactionId: 'TXN-40001',
      bookingId: 'BFLCOMEINSMAC004',
      containerId: 'OOLU1122334',
      transactionDate: '2026-08-02',
      customerVendor: 'Nordic Home Goods',
      serviceCode: 'OCEAN_FRT',
      description: 'Single 20GP Freight billing',
      transactionType: 'CUSTOMER_INVOICE',
      allocationLevel: 'CONTAINER',
      originalAmount: 5400,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-40002',
      bookingId: 'BFLCOMEINSMAC004',
      containerId: 'OOLU1122334',
      transactionDate: '2026-08-03',
      customerVendor: 'Orient Overseas Container Line',
      serviceCode: 'OCEAN_FRT',
      description: 'Carrier slot booking cost',
      transactionType: 'CARRIER_FREIGHT',
      allocationLevel: 'CONTAINER',
      originalAmount: 3600,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-40003',
      bookingId: 'BFLCOMEINSMAC004',
      containerId: '',
      transactionDate: '2026-08-04',
      customerVendor: 'Bangkok Logistics Subcontractor',
      serviceCode: 'ORIGIN_THC',
      description: 'Origin THC in Thai Baht',
      transactionType: 'TERMINAL_HANDLING',
      allocationLevel: 'BOOKING',
      originalAmount: 14000,
      currency: 'THB',
      manualFxRate: 0, // Rate 0.029 -> $406.00
    },

    // Booking 005 - Vanguard Retailers (1 container: COSU9988776)
    {
      transactionId: 'TXN-50001',
      bookingId: 'BFLCOMEINSMAC005',
      containerId: 'COSU9988776',
      transactionDate: '2026-08-06',
      customerVendor: 'Vanguard Retailers',
      serviceCode: 'OCEAN_FRT',
      description: 'Ocean freight quote invoice',
      transactionType: 'CUSTOMER_INVOICE',
      allocationLevel: 'CONTAINER',
      originalAmount: 8900,
      currency: 'USD',
      manualFxRate: 0,
    },
    {
      transactionId: 'TXN-50002',
      bookingId: 'BFLCOMEINSMAC005',
      containerId: 'COSU9988776',
      transactionDate: '2026-08-07',
      customerVendor: 'COSCO Shipping Lines',
      serviceCode: 'OCEAN_FRT',
      description: 'COSCO Vessel Freight Cost',
      transactionType: 'CARRIER_FREIGHT',
      allocationLevel: 'CONTAINER',
      originalAmount: 5800,
      currency: 'USD',
      manualFxRate: 0,
    },
  ],
  lastSaved: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
};
